#!/usr/bin/env python3
"""Write a README.md beside every shipped SKILL.md so the directory renders on GitHub.

A skill directory holds SKILL.md, which Claude Code loads and GitHub does not
render as the directory's front page. A reader arriving from a public link
saw a bare file list and no prose. README.md is generated from SKILL.md's
front-matter (name, description, version) and the skill's first heading and
paragraph, with a pointer to the full skill — one source, no second copy to
maintain. Not a symlink: the repo is cloned on Windows.

    python3 scripts/gen_skill_readmes.py          # write/refresh every README.md
    python3 scripts/gen_skill_readmes.py --check  # exit 1 if any is missing or stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS = REPO / "empirica" / "plugins" / "claude-code-integration" / "skills"
MARK = "<!-- generated by scripts/gen_skill_readmes.py from SKILL.md — edit SKILL.md, not this file -->"


def front_matter(text: str) -> dict[str, str]:
    """The YAML front-matter as flat key/value strings; enough for name,
    description and version without a YAML dependency."""
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return {}
    out: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" not in line or line.startswith((" ", "\t")):
            continue
        key, val = line.split(":", 1)
        val = val.strip()
        if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
            val = val[1:-1]
        out[key.strip()] = val
    return out


def first_section(text: str) -> tuple[str, str]:
    """The first H1 and the first non-empty paragraph after it."""
    body = re.sub(r"^---\n.*?\n---\n", "", text, count=1, flags=re.S)
    lines = body.split("\n")
    title, para, i = "", [], 0
    while i < len(lines):
        if lines[i].startswith("# "):
            title = lines[i][2:].strip()
            i += 1
            break
        i += 1
    while i < len(lines) and not lines[i].strip():
        i += 1
    while i < len(lines) and lines[i].strip() and not lines[i].startswith("#"):
        para.append(lines[i].strip())
        i += 1
    return title, " ".join(para)


def render(skill_dir: Path) -> str:
    text = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
    fm = front_matter(text)
    name = fm.get("name") or skill_dir.name
    title, para = first_section(text)
    lines = [MARK, "", f"# {title or name}", ""]
    if fm.get("description"):
        lines += [f"**When to load:** {fm['description']}", ""]
    if para:
        lines += [para, ""]
    meta = f"Skill `{name}`" + (f" · version {fm['version']}" if fm.get("version") else "")
    lines += [meta + f" · load with `/{name}` in Claude Code.", "", "Full skill: [SKILL.md](SKILL.md)", ""]
    return "\n".join(lines)


def skill_dirs() -> list[Path]:
    return sorted(p.parent for p in SKILLS.glob("*/SKILL.md"))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if any README.md is missing or stale")
    args = ap.parse_args(argv)
    stale, written = [], 0
    for d in skill_dirs():
        want = render(d)
        readme = d / "README.md"
        have = readme.read_text(encoding="utf-8") if readme.exists() else None
        if have == want:
            continue
        if args.check:
            stale.append(d.name)
        else:
            readme.write_text(want, encoding="utf-8")
            written += 1
    if args.check:
        if stale:
            print(f"stale or missing README.md in {len(stale)} skill dir(s): {' '.join(stale)}", file=sys.stderr)
            print("Run: python3 scripts/gen_skill_readmes.py", file=sys.stderr)
            return 1
        print(f"{len(skill_dirs())} skill READMEs current")
        return 0
    print(f"wrote {written} README.md file(s) across {len(skill_dirs())} skill dirs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
